### PR TITLE
Feature/reimplement nearneighbour

### PR DESCRIPTION
**Pull request by JamieJQuinn**
This PR reimplements the nearneighbour call using pyGMT's clib instead of a manual os call to gmt. This is intended to help with the performance impact of writing temporary files (see #60). Although GMT will still write to a temporary file, pyGMT uses virtual files to ensure we don't have to write the input to GMT, so some savings should come from that. Additionally, we don't have to handle temporary files ourselves.

### CODE REVIEW

**Comment by JamieJQuinn** [comment]
I'm so confused why only macos and ubuntu 3.6 are failing...

**Review by alessandrofelder — COMMENTED** [review]
Looks good to me apart from some versioning issues for `pyGMT` and Python 3.6.
Seems that the ubuntu and mac CI install `pygmt-0.2.1` which lacks some of the Clib functionality that we want to use?
Maybe worth trying to specify the minimal `pygmt` version required?

**Comment by alessandrofelder** [comment]
(Also at a later timepoint/if we have time, it might be cool to move this implementation into `pygmt` itself)

**Review by alessandrofelder — DISMISSED** [review]
Installing `pygmt>=0.3.1` seems to have done the trick.
@JamieJQuinn can you update this in the README instructions on how to create an appropriate conda environment too, please, and then merge?
@Devaraj-G if you've got a `pygmt` version <0.3.1 in your cascadia conda environment (check this with `conda list` and then scroll down to `p`), the easiest solution is to remove [your conda environment (`conda env remove -n cascadia`)](https://stackoverflow.com/questions/49127834/removing-conda-environment#49128056) and then re-create it following the instructions in the README, after this is merged (if you're using Python 3.9 you can ignore this).

**Comment by Devaraj-G** [comment]
@Alessandro `pygmt ` version is 0.3.1. Thanks for the heads-up. Proper to have it in the README.

**Comment by JamieJQuinn** [comment]
Perhaps could have been its own PR but I've added `environment.yml` which is the equiv of requirements.txt for conda. Should simplify both the install instructions (which have been updated) and the CI (which has been updated).

**Comment by JamieJQuinn** [comment]
Phew! That could have gone better... @alessandrofelder take a look and reapprove if you're happy.

**Review by alessandrofelder — APPROVED** [review]
Awesome! Love how nicely this simplifies the setup instructions.

**Pull request merged**
